linters-settings:
  goimports:
    local-prefixes: github.com/amosehiguese/zeus-ai
  govet:
    shadow: true
  revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-naming
        - name: error-strings
        - name: errorf
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments

linters:
  disable-all: true
  enable:
    # - deadcode
    - errorlint
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
run:
  timeout: 5m
  max-same-issues: 0

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude the test file shadow warnings for defer os.Chdir
    - path: _test\.go
      text: "shadow: declaration of \"err\""
      linters: [govet]
    # Exclude security warnings for test files
    - path: _test\.go
      text: "G306: Expect WriteFile"
      linters: [gosec]